### ISSUE TITLE
Fix code scanning alert - Clear text transmission of sensitive cookie

### ISSUE THREAD

**Issue by TechDudie** [TechDudie/SoulChirp#1]
Tracking issue for:
- [x] https://github.com/TechDudie/flaskprojc/security/code-scanning/1

This issue may be resolved, if time allows.

**Comment by Hardwaregore** [comment]
Me eat cookie nom nom.
@TechDudie

**Comment by TechDudie** [comment]
Resolved.

**Comment by TechDudie** [comment]
And stop pinging me for useless reasons.

**Comment by Hardwaregore** [comment]
@TechDudie
